package stud;
// Generated Mar 14, 2016 12:50:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nextofkin generated by hbm2java
 */
@Entity
@Table(name="nextofkin"
    ,catalog="studentmanagement"
)
public class Nextofkin  implements java.io.Serializable {


     private int kinId;
     private Address address;
     private String name;
     private String surname;
     private String contactNo;
     private Set<Tenant> tenants = new HashSet<Tenant>(0);

    public Nextofkin() {
    }

	
    public Nextofkin(int kinId, String name, String surname, String contactNo) {
        this.kinId = kinId;
        this.name = name;
        this.surname = surname;
        this.contactNo = contactNo;
    }
    public Nextofkin(int kinId, Address address, String name, String surname, String contactNo, Set<Tenant> tenants) {
       this.kinId = kinId;
       this.address = address;
       this.name = name;
       this.surname = surname;
       this.contactNo = contactNo;
       this.tenants = tenants;
    }
   
     @Id 

    
    @Column(name="KinId", unique=true, nullable=false)
    public int getKinId() {
        return this.kinId;
    }
    
    public void setKinId(int kinId) {
        this.kinId = kinId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AddressId")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="Name", nullable=false, length=15)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Surname", nullable=false, length=15)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="ContactNo", nullable=false, length=10)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nextofkin")
    public Set<Tenant> getTenants() {
        return this.tenants;
    }
    
    public void setTenants(Set<Tenant> tenants) {
        this.tenants = tenants;
    }




}


