package stud;
// Generated Mar 14, 2016 12:50:58 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="studentmanagement"
)
public class Payment  implements java.io.Serializable {


     private int paymentId;
     private Contract contract;
     private Account account;
     private double paymentAmount;
     private Date paymnetDate;
     private int empId;
     private String tenantId;
     private int roomId;
     private String paymentType;

    public Payment() {
    }

	
    public Payment(int paymentId, double paymentAmount, Date paymnetDate, int empId, String tenantId, int roomId) {
        this.paymentId = paymentId;
        this.paymentAmount = paymentAmount;
        this.paymnetDate = paymnetDate;
        this.empId = empId;
        this.tenantId = tenantId;
        this.roomId = roomId;
    }
    public Payment(int paymentId, Contract contract, Account account, double paymentAmount, Date paymnetDate, int empId, String tenantId, int roomId, String paymentType) {
       this.paymentId = paymentId;
       this.contract = contract;
       this.account = account;
       this.paymentAmount = paymentAmount;
       this.paymnetDate = paymnetDate;
       this.empId = empId;
       this.tenantId = tenantId;
       this.roomId = roomId;
       this.paymentType = paymentType;
    }
   
     @Id 

    
    @Column(name="PaymentId", unique=true, nullable=false)
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contractid")
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AccountId")
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    
    @Column(name="PaymentAmount", nullable=false, precision=12)
    public double getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PaymnetDate", nullable=false, length=10)
    public Date getPaymnetDate() {
        return this.paymnetDate;
    }
    
    public void setPaymnetDate(Date paymnetDate) {
        this.paymnetDate = paymnetDate;
    }

    
    @Column(name="EmpId", nullable=false)
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }

    
    @Column(name="TenantId", nullable=false, length=15)
    public String getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    
    @Column(name="RoomId", nullable=false)
    public int getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }

    
    @Column(name="paymentType", length=25)
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }




}


