package stud;
// Generated Mar 14, 2016 12:50:58 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tenant generated by hbm2java
 */
@Entity
@Table(name="tenant"
    ,catalog="studentmanagement"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="studentNo")} 
)
public class Tenant  implements java.io.Serializable {


     private String tenantId;
     private Contract contract;
     private Nextofkin nextofkin;
     private Employee employee;
     private Address address;
     private String studentNo;
     private String name;
     private String surname;
     private Character gender;
     private String email;
     private String contactNo;
     private String schoolName;
     private String password;

    public Tenant() {
    }

	
    public Tenant(String tenantId, String email) {
        this.tenantId = tenantId;
        this.email = email;
    }
    public Tenant(String tenantId, Contract contract, Nextofkin nextofkin, Employee employee, Address address, String studentNo, String name, String surname, Character gender, String email, String contactNo, String schoolName, String password) {
       this.tenantId = tenantId;
       this.contract = contract;
       this.nextofkin = nextofkin;
       this.employee = employee;
       this.address = address;
       this.studentNo = studentNo;
       this.name = name;
       this.surname = surname;
       this.gender = gender;
       this.email = email;
       this.contactNo = contactNo;
       this.schoolName = schoolName;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="TenantId", unique=true, nullable=false, length=15)
    public String getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contractid")
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="KinId")
    public Nextofkin getNextofkin() {
        return this.nextofkin;
    }
    
    public void setNextofkin(Nextofkin nextofkin) {
        this.nextofkin = nextofkin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empid")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AddressId")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="studentNo", unique=true, length=15)
    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    
    @Column(name="name", length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=25)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="email", unique=true, nullable=false, length=35)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="contactNo", length=10)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="schoolName", length=25)
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    
    @Column(name="password", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


